<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN6vxvDx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN6vxvDx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN6vxvDx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN6vxvDx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN6vxvDx\App_KernelDevDebugContainer([
    'container.build_hash' => 'N6vxvDx',
    'container.build_id' => 'e8e2541a',
    'container.build_time' => 1584651524,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN6vxvDx');
